Financial-Times/next-graphql-api

- server/lib/backend-adapters/capi.js
- server/lib/backend-adapters/fast-ft.js
- server/lib/backend-adapters/mock-capi.js
- server/lib/backend.js
- server/lib/graphql.js
- server/routes/query.js
- test/server/lib/schema.test.js
cc: @matthew-andrews, @charypar
> Allow setting of `useElasticSearchOnAws` option on content fetches

- Makefile
- server/lib/health-checks.js
Also, more rigorous tests
fixes https://github.com/Financial-Times/next-graphql-api/issues/15
> Use concept uuid for 'by concept' test

- server/lib/cache.js
The full key wasn't really suitable for logging!
> Use nicer key for metrics

- server/lib/backend-adapters/capi.js
- server/lib/cache.js
/cc @charypar @ironsidevsquincy 
* Remove missing items from the Promise.all
* Log errors fetching content
* Only log metrics for 'fresh' when we're actually fetching content
> Handle missing articles

- server/lib/backend-adapters/capi.js
> Oops. Return item

- client/main.js
- client/main.scss
- client/playground.js
- package.json
- server/init.js
- server/routes/playground.js
- server/routes/query.js
- test/smoke.js
- views/playground.html
addresses https://github.com/Financial-Times/next-graphql-api/issues/10
> Use SSO for doc, etc access

- server/lib/cache.js
- test/server/lib/capi.test.js
* Measure the size of the cache object in graphite
* Add unit tests for CAPI fetching
> Measure cache size + unit tests

- package.json
- server/lib/backend-adapters/capi.js
- server/lib/backend.js
- server/routes/query.js
Addresses https://github.com/Financial-Times/next-graphql-api/issues/26
Depends on Financial-Times/next-ft-api-client#55
> Remove es/aws flags

- README.md
> Fix readme links (fix #35)

- server/lib/types/content.js
fixes https://app.getsentry.com/nextftcom/ft-next-graphql-api/group/97403814/
> Handle no storyPackage

- server/lib/backend.js
Fixes https://app.getsentry.com/nextftcom/ft-next-graphql-api/group/93965976/
> Handle no items passed in

- package.json
- server/init.js
- server/middleware/cors.js
- server/middleware/external-auth.js
- server/routes/query.js
- test/smoke.js
/cc @ironsidevsquincy 
* Add a GET url to query the data from client side
* GETs and POSTs to get data are now authenticated by session validation, if there is no API key passed
> Client side access

- server/middleware/cors.js
@ironsidevsquincy 
Fetch doesn't like wildcards
> Set access control to origin not wildcard

- server/lib/backend-adapters/playlist.js
cc @adgad @matthew-andrews 
Fixes https://github.com/Financial-Times/next-front-page/issues/458
> Remove from GraphQL call: Video data without renditions

- server/lib/backend-adapters/capi.js
- server/lib/schema.js
- server/lib/types/content.js
So we can get back articles related to that concept
@adgad
> Add items to concept type schema

- server/lib/backend-adapters/popular-api.js
> Popular: Don't cache the 'sliced' articles/topics

- server/lib/backend-adapters/myft.js
- server/lib/types/user.js
e.g. `/next/popular-concepts/:uuid`
> User: getting viewed from bespoke myft api endpoint

- server/middleware/cors.js
> Vary on origin if cors request

- server/init.js
- server/lib/backend-adapters/myft.js
- server/lib/types/user.js
- server/middleware/cache-control.js
- server/routes/query.js
Seeing what effect this has on performance
Also make sure server caching is turned off for User requests.
cc: @adgad
> Turn off network caching

- server/lib/backend-adapters/myft.js
- server/lib/models/legacy-tag.js
- server/lib/models/topic-cards.js
- server/lib/tap.js
- server/lib/types/user.js
> Copy myFt's topic card ordering logic for followed

- server/lib/backend-adapters/mock-capi.js
- server/lib/fixtures/searches.js
/cc @ironsidevsquincy 
Fix mockFrontPage (loses some of the mocks that weren't being used I don't think)
> Kind of fix mockFrontPage

- Makefile
- circle.yml
- nodemon.json
- package.json
- server/app.js
- server/init.js
- server/lib/backend-adapters/liveblog.js
- server/lib/backend-adapters/mock-capi.js
- server/lib/backend-adapters/mock-liveblog.js
- server/lib/cache.js
- server/lib/graphql.js
- server/middleware/external-auth.js
- server/routes/query.js
- server/setup.js
- test/setup.js
Also remove a lot of unnecessary logging (around the mock endpoints)
> Use latest logger

- package.json
- test/server/lib/schema.test.js
> Test if list is down

- server/lib/backend-adapters/todays-topics.js
> Filter out null items in todaysTopics response

- server/lib/schema.js
- test/server/lib/schema.test.js
> Remove editorsPicksFromList flag

- Makefile
- src/vcl/main.vcl
Addresses https://github.com/Financial-Times/next-graphql-api/issues/87
> Update Fastly logging

- package.json
- server/lib/backend-adapters/capi.js
> Use new lists endpoint

- server/lib/backend-adapters/capi.js
- test/server/lib/backend-adapters/capi.test.js
Reverts Financial-Times/next-graphql-api#90
> Revert "Use new lists endpoint"

- package.json
- server/lib/schema.js
- server/lib/types/basic.js
- server/lib/types/collections.js
- server/lib/types/content.js
- server/lib/types/user.js
- server/setup.js
- test/smoke.js
Also, shared fields between `Article` and `LiveBlog`
> Add `tags` field to content

- server/lib/backend-adapters/capi.js
> Up CAPI search backend cache times to 10 mintues

- client/main.js
- client/playground.js
- package.json
- server/lib/backend-adapters/capi.js
- server/lib/backend-adapters/hui.js
- server/lib/backend-adapters/liveblog.js
- server/lib/backend-adapters/popular-api.js
- server/lib/backend-adapters/video.js
- server/lib/user-auth.js
- test/server/lib/backend-adapters/popular-api.test.js
Also, get rid of `eagerFetch` for session, causing multiple 404s
> More sensible cache times

- server/lib/health-checks/capi.js
- server/routes/query.js
To diagnose all the empty query requests coming in
> Lots of logging

- package.json
- server/lib/backend-adapters/fast-ft.js
> eeh -> n-raven

- server/init.js
> added request tracing

- server/routes/query.js
Only parse query string varibales
> Handle variables correctly

- README.md
- server/init.js
- server/lib/backend-adapters/index.js
- server/routes/query.js
> getting flags from request body

- package.json
- server/init.js
- server/lib/cache.js
- server/middleware/cache-control.js
> using cache helper

- server/routes/query.js
> Incoming mock header is a string

- client/main.js
- client/main.scss
- views/playground.html
> Fix: Linting warning ('Avoid using id selectors')

- server/lib/backend-adapters/myft.js
> Handle myFT errors

- server/config/sources.js
- server/lib/schema.js
This also cleans up the two old sources no longer being used.
> Update brexit primary source

- server/lib/fixtures/lists.js
> Use curly apostrophe

- server/lib/backend-adapters/mock-capi.js
- server/lib/fixtures/lists.js
- server/lib/fixtures/pages.js
As we're now using the list endpoint for the top stories
> Mock list fixtures

- package.json
- server/lib/backend-adapters/index.js
- server/lib/backend-adapters/liveblog.js
- server/lib/backend-adapters/myft.js
- server/lib/caches/redis-cache.js
- server/lib/redis.js
- test/server/lib/caches/redis-cache.test.js
- test/server/lib/redis.test.js
> Switch completely over to using the Redis cache

- server/config/sources.js
- server/lib/backend-adapters/fast-ft.js
- server/lib/backend-adapters/index.js
- server/lib/backend-adapters/myft.js
- server/lib/schema.js
Quite a low ttl for now
Also, no need for fastFT polling (as hitting es search now)
@phamann
> Cache some of the myFT requests

- server/lib/backend-adapters/myft.js
- server/lib/types/user.js
Don't log 'No user data' error
> Tidy myFT adapter

- server/lib/schema.js
```
search(termName: "idV1", termValue: "Ng==-U2VjdGlvbnM=")
```
> Adds a new search query

- server/lib/types/content.js
To enable premium content indicator
> add webUrl property to data passed accessible for content

- server/config/sources.js
- server/lib/schema.js
- server/routes/query.js
- test/server/lib/schema.test.js
@aintgoin2goa @ironsidevsquincy
> Top stories with videos

- server/lib/types/media/image.js
@ironsidevsquincy @i-like-robots
> Encode image url

- server/init.js
/cc @ifyio 
This adds system code to the health checks for this API through the `n-express` configuration.
> add system code

- Makefile
Closes #195 
@ironsidevsquincy
> disable DNS resolution when testing

- .gitignore
- client/playground.js
- package.json
- server/lib/helpers/capify-metadata.js
- webpack.config.js
> remove console.log

- server/lib/redis.js
- test/server/lib/redis.test.js
> Enable keepalive on Redis connections

- server/lib/backend-adapters/todays-topics.js
https://sentry.io/nextftcom/ft-next-graphql-api/issues/171530984/
cc: @leggsimon
> Fix today's topics
