Financial-Times/next-graphql-api

server/lib/types/content.js
In order to fetch optimally sized images for the client's screen in an effort to reduce page size for slow networks.
=> Allow fetching raw content image for use with n-image

server/lib/backend-adapters/capi.js, test/server/lib/backend.test.js
/cc @charypar @matthew-andrews 
Addresses https://github.com/Financial-Times/next-graphql-api/issues/21
In theory, this should mean less repetition in the cache => Lower memory usage. Should be able to verify this overnight, when GraphQL has been running for a long time.
Downside to the implementation here is that initially we'd be making 10 requests to elastic search instead of one, but probably worth it for the more effective cache hit ratio.
=> Cache CAPI articles individually

Makefile, server/init.js, test/smoke.js
/cc @charypar @ironsidevsquincy @andygout 
Hopefully make it less likely to break stuff on deploys :see_no_evil: 
* Also adds the ability to specify API key as a header
TODO:
=> Add smoke test for graphql query

server/lib/backend.js, server/lib/cache.js, test/server/lib/cache.test.js
Adds an unusedStaleTtl of 30 minutes, and any cache keys that haven't been accessed since that time will be cleared.
This should hopefully clear up memory used by old list of UUIDs.
=> Clear unused cache items

server/lib/backend-adapters/capi.js, server/lib/cache.js, test/server/lib/cache.test.js
/cc @matthew-andrews @ironsidevsquincy 
Currently lists and pages catch their errors in the backend-adapter and returned undefined - which then get cached.
This change uncatches the errors so they are handled in fetcher - and ensures that undefined results never get cached.
=> Don't catch CAPI errors

server/lib/backend-adapters/hui.js, server/lib/schema.js
/cc @ironsidevsquincy @andygout @aRhombus 
Was playing around with the data, and getting most popular by industry for 1 week gives slightly more relevant results than 1 day (which tends to be just home page articles and not industry relevant).
The articles will be slightly more stale, but they were a day stale anyway, so I think it's a small price to pay for more relevance.
=> Get hui results from past week instead of day

server/config/sources.js, server/lib/health-checks/capi.js, server/lib/schema.js, server/lib/types/collections.js, test/server/lib/capi.test.js, test/server/lib/top-stories.test.js, test/smoke.js
/cc @ironsidevsquincy @matthew-andrews @andygout 
Replaces https://github.com/Financial-Times/next-graphql-api/pull/67
* Top stories can get layoutHint from lists API
* Behind frontPageMultipleLayouts flag
* Items return from old CAPI Page
* If flag is off, or list API down, `layoutHint` returns null and items still return from Page
* IF layoutHInt is `standaloneimage`, the first item returned will be taken from the list (and appended on to the page) - as picture stories aren't returned in the Pages API.
=> Layout hints

server/lib/schema.js, server/lib/types/collections.js, test/server/lib/top-stories.test.js, test/smoke.js
/cc @ironsidevsquincy 
As discussed, separates out the page from the list, meaning we can keep all flag/picture story hacks within the front page.
=> Return top stories page and list separately

server/lib/backend-adapters/capi.js, server/lib/backend-adapters/myft.js, server/lib/schema.js
Add two new graph endpoints which return concepts and content. 
- `popularReadTopicsFromMyFtApi` most read concepts within the myFT eco-system
- `popularFollowedTopicsFromMyFtApi ` most followed concepts within the myFT eco-system
In order for these to work I've had to add a `topics` method to the CAPI backend which accepts an array of concept ids and hydrates them to full concept terms via the ES interface. This requires a new version of the client with the corresponding work in [#66](https://github.com/Financial-Times/next-ft-api-client/pull/66)
=> Add most popular topic endpoints from myFT API backend

server/lib/backend-adapters/capi.js, server/lib/backend-adapters/hui.js, server/lib/schema.js
The existing HUI endpoint returns `Content` but the myFT explore page is only concerned about `Concepts`, fortunately the HUI API allows you to define which type you are interested in. Therefore I have added a new endpoint to fetch this data. We also then have to search for the real concept's as HUI sadly only returns strings.
=> Add new popularTopicsFromHui endpoint

server/lib/backend-adapters/myft.js, server/lib/types/user.js
This exposes the new experimental myFT recommendation endpoint under the `User` type. For more detail on its implementation see the corresponding PR: https://github.com/Financial-Times/next-myft-api/pull/201
=> Add new user.recommendedTopics endpoiont

server/lib/backend-adapters/index.js, server/lib/backend-adapters/todays-topics.js, server/lib/schema.js
Another experimental recommendation endpoint for myFT. We wish to get a view of the current most written about/FT view of topics. To achieve this we are taking the most frequent topics from the homepage top-stories, opinion and editors picks lists and reducing them down to a single list.
It looks scary and is a lot of requests, but all of which are heavily cached already.
=> Add new TodaysTopics endpoint

server/lib/backend-adapters/hui.js, server/lib/schema.js
Currently we limit the results from HUI before looking them up in CAPI. The CAPI lookup has potential to fail as its just string searching the `prefLabel` and not direct `id` lookups. Due to this, we are seeing empty results coming back. Therefore to increase the probability of hitting your requested limit, I am now only limiting at the last point once the concepts have be hydrated from CAPI.
/cc @keirog @ironsidevsquincy
=> Postpone point at which hui topic results are limited

server/lib/backend-adapters/todays-topics.js, server/lib/schema.js
Originally I was limiting the result set from `todaysTopics` inside the backend adaptor, that was causing the potential for a consumer to get a different cached limit to the one they had requested. Moving to the schema resolver solves this. I've also up'ed the cache time of this endpoint to ten minutes.
/cc @ironsidevsquincy @keirog
=> Fix topic caching

server/lib/user-auth.js
Trying to work out why session errors are being logged twice 
https://splunk.internal.ft.com/en-US/app/search/search?q=search%20index%3Dheroku%20source%3D%22%2Fvar%2Flog%2Fapps%2Fheroku%2Fft-next-graphql-api.log%22%20Session%20endpoint&display.page.search.mode=smart&earliest=1458061200&latest=1458064800&display.events.fields=%5B%22app%22%2C%22url%22%2C%22error_message%22%2C%22error_name%22%2C%22level%22%2C%22message%22%5D&display.general.type=events&display.visualizations.charting.chart=line&display.page.search.tab=events&sid=1458063084.138100.splunk-prod-head-03
=> Diagnose double session logging

package.json, server/lib/backend-adapters/bertha.js, server/lib/backend-adapters/index.js, server/lib/identity.js, server/lib/schema.js, server/lib/types/collections.js, server/setup.js
As discussed in person, this adds a new `Collection` type which models a collection of concepts and their aggregate article count. This is an experimental data model for new myFT collection cards, therefore the data is coming from a bertha spreadsheet for easy editing before we invest time modelling properly in CAPI.
- Add bertha backend
- Add `Collection` type
- Add `collections()` end point to fetch current list of collections
/cc @ironsidevsquincy @laurieboyes
=> Add new 'Collection' type and 'collections()' endpoint

server/lib/backend-adapters/todays-topics.js
The main change here is the ternary on line 26.
This article is coming through in today's topics but doesn't seem to exist in CAPI: bc81b5bc-1995-11e5-a130-2e7db721f996
=> gracefully handle missing article in todays topics

server/lib/schema.js, test/server/lib/schema.test.js
This allows for querying of any page that you have a `uuid` for.
```
query FrontPage {
ukSectionPage: page(uuid: "2836ebbe-cd26-11de-a748-00144feabdc0") {
items(limit: 20) {
id
title
}
}
}
```
=> Adds a generic page query

server/lib/types/content.js
Exposes `isVideo` and `videoId` properties on video articles
(Also improves `isPodcast` check)
=> expose `isVideo` and `videoId` attrs and fix `isPodcast`

server/config/sources.js
Currently set to the Top Stories list that populates the Stream Hub page for Life & Arts.
For the home page there will be a separate list.
=> Update lifestyle to new curated homepage list

server/lib/types/content.js
@andygnewman @i-like-robots 
This was incorrectly tagging articles that **_have_** videos as ones that **_are_** videos. This fix ensures it is only tagged if it **_is_** a video now.
=> added isVideo check

server/lib/backend-adapters/bertha.js, server/lib/backend-adapters/capi.js, server/lib/backend-adapters/fast-ft.js, server/lib/backend-adapters/hui.js, server/lib/backend-adapters/liveblog.js, server/lib/backend-adapters/myft.js, server/lib/backend-adapters/popular-api.js, server/lib/backend-adapters/video.js, test/server/lib/backend-adapters/capi.test.js
@ironsidevsquincy @andygnewman 
So I tested this locally (in the playground*) with videos and it was cacheing the empty array. It would cache and then every new request would just return the cached array and wouldn't attempt to fetch any new data until the `ttl` had expired and a new request was made. 
After these changes, once the cached data had expired each time I made a new request it would try and fetch the data from the source, if that then became successful it would cache it.
I'm reasonably confident that this should work in all the places I've made changes. But maybe more local testing should happen so the whole world doesn't fall over.
There was a test in `capi.test.js` but I wonder whether there should be some unit tests for all the others. Thoughts?
_\* If the video fetch …
=> Dont cache empty data

package.json, server/lib/user-auth.js, test/server/lib/user-auth.test.js
Refactor the user-auth lib to use the session decoder instead of hitting the session service via HTTP.
N.b.
I am commenting out the tests as a temporary resolution so we can ship this to measure impact.
=> Session decoder

server/lib/caches/mem-cache.js, server/lib/caches/redis-cache.js
To prevent requesting the same data from a backend multiple times within a short period of time (i.e. if two identical requests came in within a couple of ms) we memoize the fetch promise in an internal object and return the original promise value if the key exists. We then purge the key once the backend has resolved with data or failed, ready for the next request of the same key to start a fresh promise. 
It turns out we are not correctly purging the key if the backend response was successful but returned no data. For instance, a 404 if the user has no myFT data :wink: 
This could potentially lead to the `currentRequests` object bloating and causing a memory leak. It could also mean a request could forever result in a resolved promise with no data.
This - quite simply - fixes that.
=> Ensure cache fetch promise is deleted if no response data returned

server/config/sources.js, server/lib/schema.js
TODO:
The reason I have duplicated `opinion` with `oldOpinion` is so that we should have no downtime. See below
**Release plan:**
/cc @ironsidevsquincy can you just clarify that this release plan is accurate. Context: Mus wants to have region specific opinion lists.
=> Add opinion & highlights variants

server/lib/types/media/image.js
We launched the new image service 6 days ago, I'm currently going around FT projects and helping them migrate to it.
The new Image Service includes a lot of improvements:
- The application is multi-region with failover
- We use stale-on-error and stale-while-revalidate cache extensions to ensure users get stale content if the application errors or has to revalidate an image
- We serve much smaller WebP and JPEG XR images to supported browsers
- We’ve seen a reduction in file size for a large number of image requests
- We’re now serving images over H2
=> move to new image service
